### ISSUE TITLE
Is there a typo in hull.py

### ISSUE THREAD

**Issue by Phonicavi** [swapnil96/Convex-hull#1]
Sorry for bothering! I was wondering whether there is a typo in the `hull.py` file, line:190:
in function `def distLine(pointA, pointB, pointX)`

```python

	vec1 = pointX - pointA
	vec2 = pointX - pointB
	vec3 = pointB - pointA
	vec4 = cross(vec1, vec2)
	if vec2.length() == 0:
		return None

	else:
		return vec4.length()/vec2.length()

```
You have calculated `vec3` but never use it. I think for a line-segment from pointA to pointB, the distance from pointX should be:

```python

	if vec3.length() == 0:
		return None

	else:
		return vec4.length()/vec3.length()

``` 
:)

**Comment by swapnil96** [comment]
Looking at this after a long time so I might be rusty in coordinate geometry now

But it seems
What you have written is correct along with that **vec4 = cross(vec1, vec3)**
I don't know why it didn't come up during testing or not pointed by anyone till now.

Can you create a pull request with necessary changes
1) Remove vec2
2) Rename vec3 as vec2, vec4 as vec3
3) Accordingly the if-else thing

**Comment by Phonicavi** [comment]
Thanks for your replying. 

Suppose we have a triangle denoted as **ABX**, with vectors **vec1** = **\vec{AX}**, **vec2** = **\vec{BX}**, **vec3** = **\vec{AB}**, and **vec4** = cross(**vec1**, **vec2**). 
Let **\theta** be the angle between \vec{XA} and \vec{XB}, the norm of **vec4** is actually **|AX|** * **|BX|** * sin(**\theta**).
Consider the area of triangle **ABX**, suppose the distance from point **X** to line **AB** is _d_, then the area **T** = 0.5 * **|AB|** * _d_, where the base **|AB|** is the norm of **vec3**. Again the area of the triangle can also be computed by **T** = 0.5 * **|AX|** * **|BX|** * sin(**\theta**), see [https://en.wikipedia.org/wiki/Law_of_sines#Relationship_to_the_area_of_the_triangle](url). 

Thus _d_ can be computed as **|AX|** * **|BX|** * sin(**\theta**) / **|AB|**, which is exactly the norm of **vec4** / the norm of **vec3**. Besides if the norm of **vec3** is zero (i.e. point **A** and point **B** converge into the same position) there is no line segment any more. :)

**Comment by swapnil96** [comment]
Yep, correct again, so there are 2 ways to close this issue

1) Either we implement the way I mentioned last time, it will take more changes but it will use only 2 vectors and a cross product, not that it matters for time complexity or such, just that it will use the area of a [parallelogram formula](https://www.qc.edu.hk/math/Advanced%20Level/Point_to_line.htm)

2) We just change the typo of vec2 to vec3 and we are done.

I think I will also go with method 2. If that is all I will close the issue by making that change

**Comment by Phonicavi** [comment]
Method 2 looks good to me, thank you!

**Comment by swapnil96** [comment]
https://github.com/swapnil96/Convex-hull/commit/22e3e3a21bb34dba06f3a7853b5504edf3a7f18f
